# Generated by Django 5.2.16 on 2026-07-24 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('GB', 'United Kingdom'), ('IE', 'Ireland'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('IN', 'India'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates'), ('ZA', 'South Africa'), ('FR', 'France'), ('DE', 'Germany'), ('ES', 'Spain'), ('IT', 'Italy'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('LU', 'Luxembourg'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('DK', 'Denmark'), ('SE', 'Sweden'), ('NO', 'Norway'), ('FI', 'Finland'), ('IS', 'Iceland'), ('PL', 'Poland'), ('CZ', 'Czechia'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('GR', 'Greece'), ('HR', 'Croatia'), ('SI', 'Slovenia'), ('EE', 'Estonia'), ('LV', 'Latvia'), ('LT', 'Lithuania'), ('CY', 'Cyprus'), ('MT', 'Malta'), ('MX', 'Mexico'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('HK', 'Hong Kong'), ('TW', 'Taiwan'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('LK', 'Sri Lanka'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('BH', 'Bahrain'), ('OM', 'Oman'), ('IL', 'Israel'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('MA', 'Morocco')], default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='town / city'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\s\\-]{1,9}$', 'Enter a valid postal / PIN code, e.g. SW1A 1AA or 560001.')], verbose_name='postal / PIN code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s\\-()]{6,19}$', 'Enter a valid phone number — 7–20 digits, e.g. +44 7700 900123.')]),
        ),
    ]
