# Generated by Django 5.2.16 on 2026-07-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'journal categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='footer', max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_text', models.CharField(blank=True, default='Complimentary UK delivery on orders over £50', max_length=255)),
                ('announcement_href', models.CharField(blank=True, max_length=255)),
                ('announcement_active', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('usp_items', models.JSONField(blank=True, default=list, help_text='[{"icon": "truck", "label": "Free UK delivery"}]')),
                ('social_instagram', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_pinterest', models.URLField(blank=True)),
                ('footer_links', models.JSONField(blank=True, default=list, help_text='[{"title": "Help", "links": [{"label": "FAQs", "href": "/faqs"}]}]')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "...", "group": "Orders"}]')),
                ('contact_email', models.EmailField(blank=True, default='hello@lavenderhill.example', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('studio_address', models.TextField(blank=True)),
                ('about_body', models.TextField(blank=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('category_tiles', 'Category tiles'), ('collection_row', 'Collection product row'), ('editorial', 'Editorial banner'), ('fabric_row', 'Fabric row'), ('journal', 'Journal preview'), ('instagram', 'Instagram grid'), ('sustainability', 'Sustainability band')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.collection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text='HTML or Markdown')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('read_minutes', models.PositiveIntegerField(default=4)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.journalcategory')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
