# Generated by Django 5.2.16 on 2026-07-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_status(apps, schema_editor):
    """Existing reviews predate the workflow: an approved one is 'approved',
    everything else starts 'pending'. Seed a matching history event so the
    timeline isn't empty for legacy reviews."""
    Review = apps.get_model("catalog", "Review")
    ReviewEvent = apps.get_model("catalog", "ReviewEvent")
    for review in Review.objects.all():
        review.status = "approved" if review.is_approved else "pending"
        review.save(update_fields=["status"])
        ReviewEvent.objects.create(
            review=review,
            action="approved" if review.is_approved else "submitted",
            rating=review.rating,
            title=review.title,
            body=review.body,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Changes requested')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Changes requested')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.review')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
